In [13]:
import numpy as np
import networkx as nx
import cvxpy as cp
import pprint

In [14]:
G = nx.DiGraph([[1, 2], [1, 3], [1, 4], [2, 6], [2, 3], [2, 4], [3, 5], [3, 6], [4, 6], [4, 7], [5, 8], [5, 7], [6, 7], [6, 8], [7, 8], [7, 9], [8, 9], [7, 10], [8, 10], [9, 10]])
aa = [1900.25857029435, 462.277027148576, 1213.68516708357, 971.9649374186, 1782.5979322978, 1524.19366605479, 912.9353303366829, 37.0072864964488, 1642.8143285905098, 889.4067287063881, 1230.8646962001899, 1583.8740748540702, 1843.6259414896099, 1476.41449162133, 352.532288989236, 811.4124261241909, 1870.93939821521, 1833.80887982682, 820.540413981891, 1787.29906182707]
tm = [1.05789130478427, 1.352868132217, 1.81316649730376, 1.00986130066092, 1.13889088195695, 1.20276521856027, 1.19872174266149, 1.60379247919382, 1.27218792496996, 1.19881426776106, 1.01527392702904, 1.74678567656443, 1.44509643228795, 1.93181457846166, 1.46599434167542, 1.41864946772751, 1.84622141782432, 1.52515249630517, 1.20264735765039, 1.67213746847429]

In [15]:
A = nx.incidence_matrix(G,oriented=True).toarray()
#A = nx.adjacency_matrix(G).toarray()
n,m = A.shape
print(A)
print(n,m)
print(A.T)

[[-1. -1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 1.  0.  0. -1. -1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  1.  0.  0.  1.  0. -1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  1.  0.  0.  1.  0.  0. -1. -1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  1.  1.  0. -1. -1.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0. -1. -1.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  1. -1. -1. -1.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  1.  0.  0. -1.
  -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  1.
   0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.
   1.  1.]]
10 20
[[-1.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0. 

In [16]:
paths = nx.all_simple_paths(G,1,10)
pprint.pprint(list(paths))

[[1, 2, 6, 7, 8, 9, 10],
 [1, 2, 6, 7, 8, 10],
 [1, 2, 6, 7, 9, 10],
 [1, 2, 6, 7, 10],
 [1, 2, 6, 8, 9, 10],
 [1, 2, 6, 8, 10],
 [1, 2, 3, 5, 8, 9, 10],
 [1, 2, 3, 5, 8, 10],
 [1, 2, 3, 5, 7, 8, 9, 10],
 [1, 2, 3, 5, 7, 8, 10],
 [1, 2, 3, 5, 7, 9, 10],
 [1, 2, 3, 5, 7, 10],
 [1, 2, 3, 6, 7, 8, 9, 10],
 [1, 2, 3, 6, 7, 8, 10],
 [1, 2, 3, 6, 7, 9, 10],
 [1, 2, 3, 6, 7, 10],
 [1, 2, 3, 6, 8, 9, 10],
 [1, 2, 3, 6, 8, 10],
 [1, 2, 4, 6, 7, 8, 9, 10],
 [1, 2, 4, 6, 7, 8, 10],
 [1, 2, 4, 6, 7, 9, 10],
 [1, 2, 4, 6, 7, 10],
 [1, 2, 4, 6, 8, 9, 10],
 [1, 2, 4, 6, 8, 10],
 [1, 2, 4, 7, 8, 9, 10],
 [1, 2, 4, 7, 8, 10],
 [1, 2, 4, 7, 9, 10],
 [1, 2, 4, 7, 10],
 [1, 3, 5, 8, 9, 10],
 [1, 3, 5, 8, 10],
 [1, 3, 5, 7, 8, 9, 10],
 [1, 3, 5, 7, 8, 10],
 [1, 3, 5, 7, 9, 10],
 [1, 3, 5, 7, 10],
 [1, 3, 6, 7, 8, 9, 10],
 [1, 3, 6, 7, 8, 10],
 [1, 3, 6, 7, 9, 10],
 [1, 3, 6, 7, 10],
 [1, 3, 6, 8, 9, 10],
 [1, 3, 6, 8, 10],
 [1, 4, 6, 7, 8, 9, 10],
 [1, 4, 6, 7, 8, 10],
 [1, 4, 6, 7, 9, 10],
 [1, 4, 6, 7, 1

In [17]:
def optPath(G,p):
    edge2ind = {e:i for i,e in enumerate(G.edges())}
    H = G.copy()
    p = np.minimum(p,1)
    w = -np.log(p)
    n = H.number_of_nodes()
    
    for i in H:
        for j in H[i]:
            H[i][j]['w'] = w[edge2ind[(i,j)]]
            
    path = nx.shortest_path(H,1,n,'w')
    foo = [edge2ind[(i,j)] for i,j in zip(path[:-1],path[1:])]
    x = np.zeros_like(p)
    x[foo] = 1
    return x

In [18]:
b = np.zeros(n)
b[0] = -1
b[n-1] = 1
print(b)

#c = np.log(p)

edge2ind = {e: i for i,e in enumerate(G.edges())}
print(edge2ind)


[-1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
{(1, 2): 0, (1, 3): 1, (1, 4): 2, (2, 6): 3, (2, 3): 4, (2, 4): 5, (3, 5): 6, (3, 6): 7, (4, 6): 8, (4, 7): 9, (6, 7): 10, (6, 8): 11, (5, 8): 12, (5, 7): 13, (7, 8): 14, (7, 9): 15, (7, 10): 16, (8, 9): 17, (8, 10): 18, (9, 10): 19}


In [19]:
nu = cp.Variable(n)
r = cp.Variable(m)
a = np.array(aa)
print(a)
t = np.array(tm)
print(t)
print(cp.mul_elemwise(a,r))
print(nu.T*b)
#cp.mul_elemwise(a,r)

constr = [A.T*nu >= -cp.mul_elemwise(a,r), cp.cumsum(r)<=9.999999, r >= 0, r <= t]
#constr = [cp.cumsum(r)<=9.999999, r >= 0, r <= t]

cp.Problem(cp.Minimize(nu.T*b),constr).solve(verbose=True)
#cp.Problem(cp.Minimize(cp.Maximize(-cp.mul_elemwise(a,r))))
print(cp.mul_elemwise(a,r))
nu = np.array(nu.value).flatten()
r = np.array(r.value).flatten()

[1900.25857029  462.27702715 1213.68516708  971.96493742 1782.5979323
 1524.19366605  912.93533034   37.0072865  1642.81432859  889.40672871
 1230.8646962  1583.87407485 1843.62594149 1476.41449162  352.53228899
  811.41242612 1870.93939822 1833.80887983  820.54041398 1787.29906183]
[1.0578913  1.35286813 1.8131665  1.0098613  1.13889088 1.20276522
 1.19872174 1.60379248 1.27218792 1.19881427 1.01527393 1.74678568
 1.44509643 1.93181458 1.46599434 1.41864947 1.84622142 1.5251525
 1.20264736 1.67213747]
mul_elemwise([[1900.25857029]
 [ 462.27702715]
 [1213.68516708]
 [ 971.96493742]
 [1782.5979323 ]
 [1524.19366605]
 [ 912.93533034]
 [  37.0072865 ]
 [1642.81432859]
 [ 889.40672871]
 [1230.8646962 ]
 [1583.87407485]
 [1843.62594149]
 [1476.41449162]
 [ 352.53228899]
 [ 811.41242612]
 [1870.93939822]
 [1833.80887983]
 [ 820.54041398]
 [1787.29906183]], var27)
var26.T * [[-1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]]

ECOS 2.0.7 - (C) embotech GmbH, Zurich Switzerla

In [20]:
print(r)
for i in range(len(r)):
    print(r[i])
print(sum(r))

[ 4.25642714e-01  1.35286813e+00  6.66425890e-01  9.64273316e-11
  1.36601213e-10  1.18131426e-09  1.19872174e+00 -2.20956327e-10
  1.30498368e-10  1.19881427e+00  1.01527393e+00  8.98038099e-01
  1.77923205e-01  1.05193635e-01  4.89925134e-01  2.76676909e-10
  6.19760956e-01  1.41163039e-10  1.20264736e+00  6.48763945e-01]
0.42564271437829904
1.3528681320470393
0.6664258895290139
9.642733162900785e-11
1.3660121289626314e-10
1.1813142621966235e-09
1.198721738242687
-2.2095632736646666e-10
1.304983681574182e-10
1.1988142663663086
1.015273926961195
0.898038098749396
0.17792320529359434
0.10519363549609605
0.48992513412211974
2.766769088746343e-10
0.6197609559918755
1.411630387875109e-10
1.2026473576581307
0.6487639449729389
9.999999001550421


In [21]:
print(nu)

[  923.38426857   114.55305311   297.98441039   114.55305174
   297.98441049  -796.37101554  -951.68042311 -1124.39485202
  -951.68042293 -2111.21561274]


In [22]:
print(np.exp(nu.dot(b)/1000))
print(nu)
print(b)

0.0480939022955161
[  923.38426857   114.55305311   297.98441039   114.55305174
   297.98441049  -796.37101554  -951.68042311 -1124.39485202
  -951.68042293 -2111.21561274]
[-1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]


In [23]:
p = np.exp(-a*r/1000)
print(p)

[0.44537831 0.53504744 0.44537831 1.         1.         1.
 0.33475531 1.         1.         0.3443029  0.28660084 0.2411396
 0.72034585 0.85615024 0.84137785 1.         0.31363193 1.
 0.3727599  0.31363193]


In [18]:
arr =  optPath(G,p)